name: Release Storages

on:
  release:
    types: [published]
  workflow_dispatch:

env:
  CI: true
  PNPM_CACHE_FOLDER: .pnpm-store
jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          registry-url: https://registry.npmjs.org
          cache: pnpm
      - run: npm i -g pnpm
      - uses: pnpm/action-setup@v4
        with:
          run_install: true
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm config set store-dir $PNPM_CACHE_FOLDER
      - run: pnpm run build
      - run: pnpm run test
      - name: create and publish versions
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm publish --no-git-checks -r
